commands_async/urls.py
# coding=utf-8
try:
    from django.urls import include, re_path as url
except ImportError:
    from django.conf.urls import url, include
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from . import views, settings

__author__ = 'alex'


cmd_patterns = ([
    url(r'^$', login_required(never_cache(views.TaskFormView.as_view()),
                              login_url=settings.COMMANDS_ASYNC_LOGIN_URL),
        name='index'),
    url(r'^status/(?P<task_id>.*)', never_cache(views.TaskFormStatus.as_view()),
        name='status'),
    url(r'^workers/status/$', login_required(never_cache(views.CeleryWorkerStatus.as_view())),
        name='workers'),
], 'command-async')

urlpatterns = [
    url(r'^command/async/', include(cmd_patterns)),
]

commands_async/models.py
from django.db import models

commands_async/forms.py
from django import forms
import ast


class TaskForm(forms.Form):
    """ Form that displays the task list """

    app_command = forms.CharField(max_length=255,
                                  required=True,
                                  widget=forms.HiddenInput())

    args = forms.CharField(max_length=1024,
                           widget=forms.HiddenInput(),
                           required=False)

    kwargs = forms.CharField(max_length=1024,
                             widget=forms.HiddenInput(),
                             required=False)

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.app_name = None

    def clean_app_command(self):
        app_command = self.cleaned_data['app_command']
        app_command = app_command.rstrip("#")
        try:
            self.app_name, app_command = app_command.rsplit(".", 1)
        except ValueError:
            self.app_name = None
        return app_command

    def clean_args(self):
        command_args = self.cleaned_data['args']
        command_args = command_args.strip("() ")
        if isinstance(command_args, str):
            if not command_args.startswith("["):
                command_args = "[" + command_args
            if not command_args.endswith("]"):
                command_args = command_args + "]"
        try:
            command_args = tuple(ast.literal_eval(command_args))
        except Exception as err:
            raise forms.ValidationError(str(err))
        return command_args

    def clean_kwargs(self):
        command_kwargs = self.cleaned_data['kwargs']
        command_kwargs = command_kwargs.strip()
        if isinstance(command_kwargs, str):
            if not command_kwargs.startswith("{"):
                command_kwargs = "{" + command_kwargs
            if not command_kwargs.endswith("}"):
                command_kwargs = command_kwargs + "}"
        try:
            command_kwargs = ast.literal_eval(command_kwargs)
        except Exception as err:
            raise forms.ValidationError(str(err))
        return command_kwargs

commands_async/views.py
# coding=utf-8
import collections
from django.core.exceptions import PermissionDenied
from django.utils.translation import gettext as _
from django.http import JsonResponse
from django.views.generic import FormView, View
from celery.result import AsyncResult
from .forms import TaskForm
from django.core.management import get_commands
from commands_async.tasks import command_exec, logger
from celery import current_app as celery_app
from . import settings


class TaskFormView(FormView):
    """ Task execution form """

    template_name = "cmdasync/index.html"

    form_class = TaskForm
    success_url = '.'

    commands_skip = settings.COMMANDS_ASYNC_COMMANDS_IGNORE
    command_permission_name = settings.COMMANDS_ASYNC_PERMISSION_NAME

    def is_command_valid(self, command_name, app_name=None):
        items = [command_name]
        if app_name is not None:
            items.append(app_name + "." + command_name)

        def check_command_name(name):
            return str(name) not in self.commands_skip

        return all(map(check_command_name , items))

    def has_permission(self):
        if bool(self.command_permission_name):
            has_perm = self.request.user.has_perm(self.command_permission_name)
        else:
            has_perm = True
        return has_perm

    def get_context_data(self, **kwargs):
        context = super(TaskFormView, self).get_context_data(**kwargs)

        commands = collections.OrderedDict()
        commands_all = get_commands()

        # merge
        for command_name in commands_all:
            app_name = commands_all[command_name]
            items = commands.setdefault(app_name, [])
            if self.is_command_valid(command_name, app_name=app_name):
                items.append(command_name)

        # order
        for key in commands:
            commands[key].sort()

        context['commands'] = commands
        context['settings'] = settings
        return context

    def form_invalid(self, form):
        return JsonResponse({
            'form': {
                'errors': form.errors
            }
        }, status=400)

    def form_valid(self, form):
        """Executes the task"""
        app_command = form.cleaned_data['app_command']
        command_args = form.cleaned_data['args']
        command_kwargs = form.cleaned_data['kwargs']

        if not self.is_command_valid(app_command, app_name=form.app_name) or not self.has_permission():
            if not self.request.is_ajax():
                raise PermissionDenied  # Can not execute this command.
            else:
                return JsonResponse({
                    'form': {'errors': {'app_command': [_("not allowed to run this command")]}}
                }, status=400)
        try:
            task = command_exec.apply_async(args=(app_command,) + command_args,
                                            kwargs=command_kwargs,
                                            priority=settings.COMMANDS_ASYNC_TASK_PRIORITY)
        except:
            logger.exception('failed to execute {0!s}'.format(app_command))
            task = None
        if task is None:
            return JsonResponse({
                'form': {
                    'errors': {'app_command': [
                        _("command %(command)s failed to execute") % {'command': app_command}
                    ]}
                }
            }, status=400)
        return JsonResponse({
            'task': {
                'id': task.id,
                'command': {
                    'name': app_command
                }
            }
        })


class CeleryWorkerStatus(View):
    """Reports status of workers celery"""
    def get(self, request, **kwargs):
        data = {'status': True, 'workers': []}
        try:
            for worker in celery_app.control.inspect().active():
                data['workers'].append(worker)
        except Exception as err:
            data['status'] = False
            data['message'] = str(err)
        return JsonResponse(data)


class TaskFormStatus(View):

    def get(self, request, **kwargs):
        """Reports task status"""
        task_id = str(kwargs.get("task_id"))
        async_result = AsyncResult(id=task_id, app=celery_app)
        data = {
            'task': {
                'id': async_result.id,
                'ready': async_result.ready(),
            }
        }
        if async_result.failed():
            data['task']['failed'] = True
            data['task']['traceback'] = async_result.traceback
        else:
            data['task']['failed'] = False
            data['task']['output'] = async_result.result
        return JsonResponse(data)

    def post(self, request, **kwargs):
        task_id = kwargs.get('task_id')
        try:
            celery_app.control.revoke(task_id, terminate=True)
            data = {"status": True}
        except Exception as err:
            data = {"status": False, "error": str(err)}
        return JsonResponse(data)

commands_async/templates/cmdasync/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static "cmdasync/bootstrap-4.3.1/css/bootstrap.min.css" %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="{% static "cmdasync/js/html5shiv.min.js" %}"></script>
      <script src="{% static "cmdasync/js/respond.min.js" %}"></script>
    <![endif]-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static "cmdasync/js/jquery-3.2.1.min.js" %}"></script>

    <script src="{% static "cmdasync/js/jquery.form.v4.4.2.min.js" %}"></script>

    <script src="{% static "cmdasync/bootstrap-4.3.1/js/util.js" %}"></script>
    <title>{% block title %}{% endblock %}</title>
    {% block extrahead %}{% endblock %}
</head>
<body>
{% block body %}{% endblock %}
<script src="{% static "cmdasync/bootstrap-4.3.1/js/popper.min.js" %}"></script>
<script src="{% static "cmdasync/bootstrap-4.3.1/js/bootstrap.min.js" %}"></script>
</body>
</html>

commands_async/templates/cmdasync/form-dropdown.html
{% load i18n %}
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle btn-md"
            type="button"
            id="task-app-command"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="true">
        <span class="info">{% trans "Choose one" %}</span>
        <span class="glyphicon glyphicon-menu-down"></span>
    </button>
    <div class="dropdown-menu" aria-labelledby="task-app-command">
        {% for app_name, values in commands.items %}
            <h6 class="dropdown-item">{{ app_name|upper }}</h6>
            {% for cmd in values %}
                <a class="dropdown-item" href="#{{ app_name }}.{{ cmd }}">{{ cmd|lower }}</a>
            {% endfor %}
            <div class="dropdown-divider"></div>
        {% endfor %}
    </div>
</div>

commands_async/templates/cmdasync/index.html
{% extends "cmdasync/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Run tasks" %}{% endblock %}

{% block extrahead %}
       <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static "cmdasync/styles.css" %}">
    <script type="application/javascript" src="{% static "cmdasync/js/cmdhandler.js" %}"></script>
    {% if settings.COMMANDS_ASYNC_WORKERS_STATUS_CHECK %}
    <script type="application/javascript" src="{% static 'cmdasync/js/celery.workers.status.js' %}"></script>
    {% endif %}
    <script type="application/javascript">
        $(document).ready(function () {
            {% if settings.COMMANDS_ASYNC_WORKERS_STATUS_CHECK %}
            workers_check_status();
            {% endif %}
            cmdasyncform.init("#task-output");
            var rel_inputs = {
                'args': 'task-args',
                'kwargs': 'task-kwargs',
                'app_command': 'task-app-command'
            };
            $("#task-copy").click(function(){
               cmdasyncform.copyToClipboard("#task-output");
            });
            // passing parameters.
            $("#task-args").change(function(){ $("#id_args").val($(this).val());});
            $("#task-kwargs").change(function(){ $("#id_kwargs").val($(this).val());});
            // show/hide copy button
            $("#task-app-command").focusin(function () {
                $("#task-copy").addClass("d-none");
            }).focusout(function () {
                if ($("#task-output").text().length > 0)
                    $("#task-copy").removeClass("d-none");
            });
            var $btnSubmit = $("#btn-task-submit");
            $btnSubmit.click(function() {
                $(this).find(".task-progress").removeClass("d-none");
                $("#task-copy").addClass("d-none");
                cmdasyncform.clear_output();
            });
            {% if settings.COMMANDS_ASYNC_LIST %}
            $(".dropdown-menu > a").on('click', function () {
                var value = $(this).attr("href");
                value = value.substring(1, value.length);

                var items = value.split(".");
                var app_command = items[items.length-1];
                var app_name = items.slice(0, -1).join(".").toUpperCase();

                $("#form-app_name").html(app_name);
                $("#task-app-command").find("> span.info").html(app_command);

                $("input#id_app_command").val(value);
                // stop status update
                cmdasyncform.update_abort();
                cmdasyncform.clear_output();
            });
            {% else %}
            $btnSubmit.click(function(){
                $("#id_app_command").val($("#task-app-command").val());
            });
            {% endif %}

            $("#btn-task-cancel").click(function () {
                var $btnCancel = $(this).prop('disabled', true);
                $btnCancel.find(".task-progress").removeClass("d-none");
                cmdasyncform.update_abort();
            });

            $("#btn-task-revoke").click(function () {
                var $btnRevoke = $(this).prop('disabled', true);
                $btnRevoke.find(".task-progress").removeClass("d-none");
                cmdasyncform.revoke_task.bind(cmdasyncform)();
            });

            var requestErrorClean = function() {
                $(".invalid-feedback").remove();
                for (var name in rel_inputs) {
                    $("#" + rel_inputs[name]).removeClass("is-invalid");
                }
            };

            var requestUpdateFinish = function() {
                var $btnSubmit = $('#btn-task-submit').prop('disabled', false);
                $btnSubmit.find(".task-progress").addClass("d-none");

                var $btnCancel = $("#btn-task-cancel").prop('disabled', true);
                $btnCancel.find(".task-progress").addClass("d-none");

                var $btnRevoke = $("#btn-task-revoke").prop('disabled', true);
                $btnRevoke.find(".task-progress").addClass("d-none");

                // show/hide copy button
                $("#task-copy")[$("#task-output").text().length > 0 ? "removeClass" : "addClass"]("d-none");
            };

            cmdasyncform.ajax("form#taskform", {
                beforeSubmit: function(arr, $form, options) {
                    var $btnSubmit = $form.find('#btn-task-submit');
                    if ($btnSubmit.attr('disabled'))
                        return false;
                    $btnSubmit.prop('disabled', true);
                    $form.find("#btn-task-cancel").prop('disabled', false);
                    $form.find("#btn-task-revoke").prop('disabled', false);
                },
                error: function(xhr) {
                    requestErrorClean();
                    switch (xhr.status) {
                        case 200:  // need login
                            var url = ["{{ settings.COMMANDS_ASYNC_LOGIN_URL }}"];
                            url.push("?{{ settings.COMMANDS_ASYNC_REDIRECT_FIELD_NAME }}=");
                            url.push("{% url 'command-async:index' %}");
                            window.location = url.join("");
                            break;
                        case 400:
                            var $input, data = xhr.responseJSON;
                            var $feedback = $('<div class="invalid-feedback"></div>');
                            for (var name in data.form.errors) {
                                $input = $("#" + rel_inputs[name]);
                                $input.addClass("is-invalid");
                                $input.parent().append($feedback.clone().html(data.form.errors[name][0]));
                            }
                            break;
                    }
                    requestUpdateFinish();
                }
            });
            cmdasyncform.add_event_callback("updating", function($form) {
                $("#task-output").text("{% trans "Running command..." %}");
            });
            cmdasyncform.add_event_callback("form-valid",
                function(responseText, statusText, xhr, $form) {
                requestErrorClean();
            });
            cmdasyncform.add_event_callback("update-finish",
                function(form) {
                requestUpdateFinish();
            })
        });
    </script>
{% endblock %}

{% block body %}
{% include 'cmdasync/toast.html' %}

<div class="container" id="wrap">
    <div class="card" id="task-panel">
        <div class="card-body">
            {% block panelbody %}
            <h4>{% trans "Checking and updating environment" %}</h4>
            <p>
                <strong>{% trans "Atenção:" %}</strong>
                {% trans "It is strongly recommended that the systembe usedwith the aid of an approved technician." %}
            </p>
            {% endblock %}
            <form id="taskform" action="." method="post">{% csrf_token %}
                <div class="form-group">
                    <div class="input-group mb-1">
                        <div class="input-group-prepend">
                            <div class="input-group-text" id="form-app_name">{% trans "COMMAND" %}</div>
                        </div>
                        {% if settings.COMMANDS_ASYNC_LIST %}
                            {% include "cmdasync/form-dropdown.html" %}
                        {% else %}
                            <label for="task-app-command"></label>
                            <input type="text" id="task-app-command" class="form-control" autocomplete="on"
                                   placeholder="{% trans "Execute a command" %}" aria-describedby="form-app_name">
                        {% endif %}
                    </div>
                    {% include 'cmdasync/response-form-task-args-lg.html' %}
                    {% include 'cmdasync/response-form-task-args-md.html' %}
                </div>
                <div class="form-group">
                    {{ form.as_ul }}
                    <button class="btn btn-success" type="submit" id="btn-task-submit">
                      <span class="spinner-grow spinner-grow-sm d-none task-progress" role="status" aria-hidden="true"></span>
                      Execute
                    </button>

                    <button class="btn btn-warning" type="button" id="btn-task-cancel" disabled>
                        <span class="spinner-grow spinner-grow-sm d-none task-progress" role="status" aria-hidden="true"></span>
                        {% trans "Cancel" %}
                    </button>

                     <button class="btn btn-danger" type="button" id="btn-task-revoke" disabled>
                        <span class="spinner-grow spinner-grow-sm d-none task-progress" role="status" aria-hidden="true"></span>
                        {% trans "Revoke" %}
                    </button>
                </div>
            </form>
        </div>
        <div class="card-footer">
            <pre id="task-output"></pre>
            <div class="input-group">
            <input type="button" id="task-copy" class="btn btn-primary btn-sm d-none" value="{% trans "Copy" %}">
            </div>
        </div>
    </div>
</div>
{{ body.super }}
{% endblock %}

commands_async/templates/cmdasync/response-form-task-args-lg.html
{% load static %}
{% load i18n %}
<div class="form-row form-task-args-lg">
    <div class="col">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text" id="btnGroupAddon">{% trans "args" %}</div>
            </div>
            <label for="task-args"></label>
            <input type="text" id="task-args" class="form-control" autocomplete="off"
                   placeholder="{% trans "Insert arguments" %}" aria-describedby="btnGroupAddon">
        </div>
    </div>
    <div class="col">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text" id="btnGroupAddon1">{% trans "kwargs" %}</div>
            </div>
            <label for="task-kwargs"></label>
            <input type="text" id="task-kwargs" class="form-control" autocomplete="off"
                   placeholder="{% trans "Insert arguments" %}" aria-describedby="btnGroupAddon1">
        </div>
    </div>
</div>

commands_async/templates/cmdasync/response-form-task-args-md.html
{% load static %}
{% load i18n %}
<div class="form-group form-task-args-md">
    <div class="input-group mb-1">
        <div class="input-group-prepend">
            <div class="input-group-text" id="btnGroupAddon">{% trans "args" %}</div>
        </div>
        <label for="task-args"></label>
        <input type="text" id="task-args" class="form-control" autocomplete="off"
               placeholder="{% trans "Insert arguments" %}" aria-describedby="btnGroupAddon">
    </div>

    <div class="input-group">
        <div class="input-group-prepend">
            <div class="input-group-text" id="btnGroupAddon1">{% trans "kwargs" %}</div>
        </div>
        <label for="task-kwargs"></label>
        <input type="text" id="task-kwargs" class="form-control" autocomplete="off"
               placeholder="{% trans "Insert arguments" %}" aria-describedby="btnGroupAddon1">
    </div>
</div>

commands_async/templates/cmdasync/toast.html
<div class="toast fade" data-delay="5000" id='popup-msg'>
    <div class="toast-header">
        <strong class="mr-auto"><i class="fa fa-grav"></i>Celery Workers Online</strong>
        <span class="badge badge-secondary online"></span>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
    </div>
    <div class="toast-body"></div>
</div>